[package]
name = "pdf-compressor"
version = "0.1.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
lto = true
strip = true

[dependencies]
dirs = "5.0.1"
eframe = "0.22.0"
env_logger = "0.10.0"
rfd = "0.11.4"
